name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          source_dir: './build'  # The directory to upload (typically your build directory)
          destination_bucket: ${{ secrets.S3_BUCKET_NAME }}  # S3 bucket name stored in secrets
          region: ${{ secrets.AWS_REGION }}  # AWS region (e.g., us-east-1)
          delete: true  # Delete files from S3 that aren't in the source_dir
          acl: public-read  # Set files to be publicly accessible
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
